version: '3.8'

services:
  dr-singh-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./chromadb:/app/chromadb
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped